export const DEFAULT_MODULES = [
  {
    id: 1,
    key: 'transactions',
    name: 'Transaksi/Penjualan',
    description: 'Checkout, keranjang belanja, hitung total, void/return, dan multi-payment',
    icon: 'ShoppingBag',
    category: 'Penjualan',
    isActive: true,
    isCore: true,
    dependencies: ['products', 'payments'],
    permissions: { admin: 'full', cashier: 'full', customer: 'none' }
  },
  {
    id: 2,
    key: 'inventory',
    name: 'Inventori & Stok',
    description: 'Daftar stok, adjustment, alert minimum, barang masuk/keluar & mutasi',
    icon: 'Layers',
    category: 'Logistik',
    isActive: true,
    isCore: false,
    dependencies: ['products'],
    permissions: { admin: 'full', cashier: 'read', customer: 'none' }
  },
  {
    id: 3,
    key: 'products',
    name: 'Produk & Katalog',
    description: 'Katalog produk, barcode SKU, kategori, harga modal & jual, upload gambar',
    icon: 'Tag',
    category: 'Master Data',
    isActive: true,
    isCore: true,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'read', customer: 'read' }
  },
  {
    id: 4,
    key: 'customers',
    name: 'Customer & Member',
    description: 'Daftar pelanggan, profil, riwayat belanja, dan status tier member',
    icon: 'Users',
    category: 'Master Data',
    isActive: true,
    isCore: false,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'full', customer: 'own' }
  },
  {
    id: 5,
    key: 'payments',
    name: 'Metode Pembayaran',
    description: 'Tunai, Kartu EDC, QRIS Dinamis, Transfer Bank, E-Wallet & Split Bill',
    icon: 'CreditCard',
    category: 'Keuangan',
    isActive: true,
    isCore: true,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'full', customer: 'none' }
  },
  {
    id: 6,
    key: 'promos',
    name: 'Diskon & Promosi',
    description: 'Voucher kode promo, diskon persentase/nominal, kuota dan periode berlaku',
    icon: 'Gift',
    category: 'Marketing',
    isActive: true,
    isCore: false,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'full', customer: 'read' }
  },
  {
    id: 7,
    key: 'reports',
    name: 'Laporan & Analitik',
    description: 'Laporan omset harian/bulanan, laba kotor, produk terlaris & kinerja kasir',
    icon: 'TrendingUp',
    category: 'Keuangan',
    isActive: true,
    isCore: false,
    dependencies: ['transactions'],
    permissions: { admin: 'full', cashier: 'own', customer: 'none' }
  },
  {
    id: 8,
    key: 'users',
    name: 'Manajemen User',
    description: 'Kelola akun user, assign role (Admin/Kasir/Customer), reset password & status',
    icon: 'ShieldCheck',
    category: 'Sistem',
    isActive: true,
    isCore: true,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'none', customer: 'none' }
  },
  {
    id: 9,
    key: 'shifts',
    name: 'Shift & Kasir',
    description: 'Buka shift, tutup shift, hitung uang fisik kas, audit selisih kas & laporan shift',
    icon: 'Clock',
    category: 'Operasional',
    isActive: true,
    isCore: false,
    dependencies: ['transactions'],
    permissions: { admin: 'full', cashier: 'full', customer: 'none' }
  },
  {
    id: 10,
    key: 'receipts',
    name: 'Struk & Invoice',
    description: 'Cetak struk thermal 58/80mm, kustom template struk toko, QRIS & digital receipt',
    icon: 'Receipt',
    category: 'Penjualan',
    isActive: true,
    isCore: false,
    dependencies: ['transactions'],
    permissions: { admin: 'full', cashier: 'full', customer: 'read' }
  },
  {
    id: 11,
    key: 'loyalty',
    name: 'Loyalty & Poin',
    description: 'Program reward poin belanja, tier member (Bronze-Platinum), redeem potongan belanja',
    icon: 'Star',
    category: 'Marketing',
    isActive: true,
    isCore: false,
    dependencies: ['customers'],
    permissions: { admin: 'full', cashier: 'full', customer: 'full' }
  },
  {
    id: 12,
    key: 'settings',
    name: 'Pengaturan Toko',
    description: 'Konfigurasi nama toko, PPN/Pajak, mata uang, printer thermal, backup JSON',
    icon: 'Settings',
    category: 'Sistem',
    isActive: true,
    isCore: false,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'none', customer: 'none' }
  },

  {
    id: 14,
    key: 'employees',
    name: 'Karyawan & Staf',
    description: 'Data staf karyawan, jadwal kerja, absensi clock-in/out, komisi penjualan',
    icon: 'Briefcase',
    category: 'SDM',
    isActive: true,
    isCore: false,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'none', customer: 'none' }
  },
  {
    id: 15,
    key: 'notifications',
    name: 'Notifikasi Sistem',
    description: 'Pusat peringatan stok menipis, transaksi besar, promo aktif, dan audit sistem',
    icon: 'Bell',
    category: 'Operasional',
    isActive: true,
    isCore: false,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'full', customer: 'own' }
  },
  {
    id: 16,
    key: 'module_management',
    name: 'Manajemen Modul',
    description: 'Kontrol aktivasi 16 modul, backup snapshot otomatis, audit log history & preset bisnis',
    icon: 'Sliders',
    category: 'Sistem',
    isActive: true,
    isCore: true,
    dependencies: [],
    permissions: { admin: 'full', cashier: 'none', customer: 'none' }
  }
];
